# Generated by Django 6.0.3 on 2026-03-16 22:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('associations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('category', models.CharField(choices=[('health', 'Santé'), ('education', 'Éducation'), ('environment', 'Environnement'), ('humanitarian', 'Humanitaire'), ('emergency', 'Urgence')], max_length=20)),
                ('deadline', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='campaigns/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='associations.association')),
            ],
            options={
                'db_table': 'campaigns',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category'], name='campaigns_categor_c36a12_idx'), models.Index(fields=['is_active'], name='campaigns_is_acti_6c57d0_idx')],
            },
        ),
    ]
