# Generated by Django 4.2.11 on 2026-03-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_avatar_remove_user_bio_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='associations/documents/'),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='cin',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
