# Generated by Django 4.2.11 on 2026-05-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_message_file_name_message_location_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
