# Generated by Django 4.2.11 on 2026-05-06 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


CREATE_CALL_SESSIONS_SQL = """
CREATE TABLE `call_sessions` (
  `id` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `call_type` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `offer_sdp` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `answer_sdp` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `caller_candidates` json NOT NULL,
  `callee_candidates` json NOT NULL,
  `started_at` datetime(6) DEFAULT NULL,
  `ended_at` datetime(6) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `callee_id` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `caller_id` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `conversation_id` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  KEY `call_sessions_callee_id_538139e8_fk_users_id` (`callee_id`),
  KEY `call_sessions_caller_id_06606568_fk_users_id` (`caller_id`),
  KEY `call_sessions_conversation_id_e32db9ae_fk_conversations_id` (`conversation_id`),
  CONSTRAINT `call_sessions_callee_id_538139e8_fk_users_id` FOREIGN KEY (`callee_id`) REFERENCES `users` (`id`),
  CONSTRAINT `call_sessions_caller_id_06606568_fk_users_id` FOREIGN KEY (`caller_id`) REFERENCES `users` (`id`),
  CONSTRAINT `call_sessions_conversation_id_e32db9ae_fk_conversations_id` FOREIGN KEY (`conversation_id`) REFERENCES `conversations` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
"""

DROP_CALL_SESSIONS_SQL = "DROP TABLE IF EXISTS `call_sessions`;"


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0004_alter_message_file_name'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=CREATE_CALL_SESSIONS_SQL,
                    reverse_sql=DROP_CALL_SESSIONS_SQL,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='CallSession',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('call_type', models.CharField(choices=[('voice', 'Voice'), ('video', 'Video')], max_length=10)),
                        ('status', models.CharField(choices=[('ringing', 'Ringing'), ('active', 'Active'), ('declined', 'Declined'), ('ended', 'Ended'), ('missed', 'Missed')], default='ringing', max_length=20)),
                        ('offer_sdp', models.TextField(blank=True, default='')),
                        ('answer_sdp', models.TextField(blank=True, default='')),
                        ('caller_candidates', models.JSONField(blank=True, default=list)),
                        ('callee_candidates', models.JSONField(blank=True, default=list)),
                        ('started_at', models.DateTimeField(blank=True, null=True)),
                        ('ended_at', models.DateTimeField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('callee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_calls', to=settings.AUTH_USER_MODEL)),
                        ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_calls', to=settings.AUTH_USER_MODEL)),
                        ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_sessions', to='messaging.conversation')),
                    ],
                    options={
                        'db_table': 'call_sessions',
                        'ordering': ['-created_at'],
                    },
                ),
            ],
        ),
    ]
