# Generated by Django 4.2.11 on 2026-03-23 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_set', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'follows',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['follower'], name='follows_followe_ca9b09_idx'), models.Index(fields=['following'], name='follows_followi_dcb467_idx')],
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
