# Generated by Django 4.2.11 on 2026-03-22 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_like_options_alter_savedpost_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
