# Generated by Django 6.0.3 on 2026-03-16 22:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='completed', max_length=20)),
                ('transaction_id', models.CharField(max_length=200, unique=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='donations', to='campaigns.campaign')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'donations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['donor', 'status'], name='donations_donor_i_9c0085_idx'), models.Index(fields=['campaign', 'status'], name='donations_campaig_59c31d_idx')],
            },
        ),
    ]
